M48
; DRILL file {KiCad (6.0.7)} date Fri Aug 12 19:29:28 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-08-12T19:29:28+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X5.2756Y-3.5039
X5.2756Y-4.9606
X7.1654Y-3.5039
X7.1654Y-4.9606
T0
M30
