name=ESP32_PPM
version=1.0
author=Cédric Henrioul <henri_oul@hotmail.com>
maintainer=Cédric Henrioul <henri_oul@hotmail.com>
sentence=Makes coding responsive sketches easier.
paragraph=This library has been modified to be usable with the RCUL protocol of RcNavy. It supports positive or negative pulses.
category=Timing
url=Based on the hx_espnow_rc library created by Romanlut
architectures=*
