name=SBUS TheDIYGuy999
version=1.1.0
author=Brian Taylor <brian.taylor@bolderflight.com>
maintainer=TheDIYGuy999
sentence=Library for communicating with SBUS receivers and servos.
paragraph=This library works with Teensy 3.x and LC devices, the STM32L4, ESP32 and the Maple Mini. Opzimised for use with ESP32.
url=https://github.com/TheDIYGuy999/SBUS
architectures=*
includes=SBUS.h